os: osx
osx_image: xcode10.1
language: swift
xcode_project: Spiffy.xcodeproj
xcode_scheme: Spiffy
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR
podfile: Podfile

before_install:
  - pod repo update